function [mdl,analysisParameters,pathSave] = doOneTouchAnalysisBDF(path)
disp('do offline anlaysis of bdf file');
[~,analysisParameters,~,winSeg] = getProcEmgDB(...
   'pathDB',path.selpath,...
   'ListSubject',1,...
   'ListSession',1,...
   'idFeatExtraction',false,...
   'idBipolarConfigure',false,...
   'idSaveDB',false);

[mdl,~] = doAnalysisRiemanAdaption(...
   'iEMGpair',analysisParameters.emgPair,...
   'winSize',analysisParameters.winSize,...
   'winSegTest',winSeg,...
   'nFE',length(analysisParameters.labelNames),...
   'TestMode','train',...
   'alphaList',0.5,...
   'betaList',0.5,...
   'pathDB','D:\research\FE_recog_offline_ver2.0\DB\DB_proc\DB_raw_demRiemannian');

% 저장하기
[pathSave,name] = fileparts(path.selpath);
save(fullfile(pathSave,[name,'_model']),'analysisParameters','mdl','winSeg');
end