function [timerReadFile,analysisParameters] = getTimerRePlayBDFTest(tf)
global path
% get Paramteres by using offline analysis
[~,analysisParameters,rawDB] = getProcEmgDB(...
   'pathDB','D:\research\FE_receog_online_ver2.0\DB\bdf\01.bdf',...
   'ListSubject',1,...
   'ListSession',1,...
   'idFeatExtraction',false,...
   'idBipolarConfigure',false,...
   'idWinExtraction',false,...
   'idSaveDB',false...
   );

% prepare timer object
delete(timerfind);
clear acqRealTimeDB;
assignin('base','analysisParameters',analysisParameters)
assignin('base','rawDB',rawDB)
timerReadFile = timer(...
   'TimerFcn','acqRealTimeDB(''analysisParameters'', analysisParameters,''rawDB'', rawDB,''idDoPredict'',true);',...
   'Period', tf,'ExecutionMode', 'fixedRate',...
   'UserData','d');
end