function [timerReadFile,analysisParameters] = getTimerRePlayBDF(tf)
% get Paramteres by using offline analysis
[~,analysisParameters,rawDB] = getProcEmgDB(...
   'pathDB',[],...
   'ListSubject',1,...
   'ListSession',1,...
   'idFeatExtraction',false,...
   'idBipolarConfigure',false,...
   'idWinExtraction',false,...
   'idSaveDB',false...
   );

% prepare timer object
delete(timerfind);
clear acqRealTimeDB;
assignin('base','analysisParameters',analysisParameters)
assignin('base','rawDB',rawDB)
timerReadFile = timer(...
   'TimerFcn','acqRealTimeDB(''analysisParameters'', analysisParameters,''rawDB'', rawDB);',...
   'Period', tf,'ExecutionMode', 'fixedRate',...
   'UserData','d');
end